#!/bin/bash
if [ $# -ne 2 ]
then
echo "Usage: batch [simulation folder] [number of samples to gather]"
exit 1
fi

#module load java

if [ "$1" != "" ]
then
  f=${1}/
else
  f=$1
fi

FILES=${f}lib/*.jar
CLASSPATH=.:${f}dist/hft.jar
for i in $FILES
do
  CLASSPATH=${CLASSPATH}:${i}
done

echo $FILES
echo $CLASSPATH

i=1
while [ $i -le $2 ]
do
    java -Xms128M -Xmx512M -cp ${CLASSPATH} systemmanager.SystemManager $i $1
    i=$((i+1))
done
