#!/bin/bash
if [ $# -ne 2 ]
then
echo "Usage: batch [simulation folder] [number of samples to gather]"
exit 1
fi

#module load java

FILES=lib/*.jar
CLASSPATH=.:dist/hft.jar
for i in $FILES
do
  CLASSPATH=${CLASSPATH}:${i}
done

i=1
while [ $i -le $2 ]
do
    java -Xms128M -Xmx512M -cp ${CLASSPATH} systemmanager.SystemManager $1 $i
    i=$((i+1))
done
