"use strict";
var jsdom = require("jsdom");
var fs = require("fs");

process.stdout.write(`Description of Simulator Keys
==============================

The market simulator uses a number of typesafe keys in order to pass parameters from a specification file to agents in the simulator.
Below is a table with all of the keys and any desription of them.
Note: This is autogenerated from the keys specification and javadocs.

Key | Type | Description
----|------|------------
`);

var keyReg = /(\w+)\.html$/;
var helpReg = /@ValueHelp\(value="[^"]+/;
var typeReg = /edu\.umich\.srg\.egtaonline\.spec\.ParsableValue<.*/;

var numKeys = process.argv.length - 2;
var keys = [];

function print() {
    if (keys.length < numKeys) {
        return;
    }
    keys.sort();
    keys.forEach(entry => {
        process.stdout.write(`\`${entry[0]}\` | \`${entry[1]}\` | ${entry[2]}\n`);
    });
}

process.argv.slice(2).forEach(filename => {
    var key = filename.match(keyReg)[1];
    fs.readFile(filename, "utf8", (err, html) => {
        jsdom.env(html, (err, window) => {
            var help = window.document.querySelector(".description pre").textContent.match(helpReg);
            var helpText = help ? help[0].slice(18) : "[No Info Provided]";
            var type = window.document.querySelector('.inheritance').textContent.match(typeReg)[0].slice(44, -1);
            keys.push([key, type, helpText]);
            print();
        });
    });
});
