repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.0.1
   hooks:
   - id: trailing-whitespace

 - repo: https://github.com/ambv/black
   rev: 21.6b0
   hooks:
   - id: black
     language_version: python3.7
     args: ["--line-length=120"]

 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v2.3.0
   hooks:
   - id: flake8
     args: ["--ignore=E226,E302,E41,E203", "--max-line-length=120", "--max-complexity=10"]

 - repo: https://github.com/pre-commit/mirrors-isort
   rev: v5.9.1
   hooks:
   - id: isort
     args: ["-p=egta,experiments", "-o=absl,gin,torch"]